global:
  scrape_interval: 5s
  evaluation_interval: 30s

rule_files:
  - "/etc/prometheus/rules/*.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["10.86.50.188:9100","10.86.50.189:19100"]
  - job_name: "etcd_cluster"
    static_configs:
      - targets: ["10.86.50.188:2379","10.86.50.188:12379","10.86.50.188:22379"]
  

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']