version: '3.8'

networks:
  monitor:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # 注意修改/prometheus/data访问权限 chmod +777 ./prometheus/data
      - ./prometheus/data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./alertmanager/template:/etc/alertmanager/template:ro
      - ./alertmanager/data:/alertmanager
    networks:
      - monitor
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # 注意修改./grafana/data访问权限 chmod +777 ./grafana/data
      - ./grafana/data:/var/lib/grafana
    networks:
      - monitor